services:
  postgres:
    image: 'postgres:16.4-alpine3.20@sha256:d898b0b78a2627cb4ee63464a14efc9d296884f1b28c841b0ab7d7c42f1fffdf'
    restart: always
    environment:
      POSTGRES_DB: speckle
      POSTGRES_USER: speckle
      POSTGRES_PASSWORD: speckle
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./setup/db/10-docker_postgres_init.sql:/docker-entrypoint-initdb.d/10-docker_postgres_init.sql
      - ./setup/db/11-docker_postgres_keycloak_init.sql:/docker-entrypoint-initdb.d/11-docker_postgres_keycloak_init.sql
    # Not exposing port 5432 on host to avoid conflicts with existing postgres
    command: postgres -c max_prepared_transactions=150

  # postgres-region1:
  #   image: 'postgres:16.4-alpine3.20@sha256:d898b0b78a2627cb4ee63464a14efc9d296884f1b28c841b0ab7d7c42f1fffdf'
  #   restart: always
  #   environment:
  #     POSTGRES_DB: speckle
  #     POSTGRES_USER: speckle
  #     POSTGRES_PASSWORD: speckle
  #   volumes:
  #     - postgres-region1-data:/var/lib/postgresql/data/
  #     - ./setup/db/10-docker_postgres_init.sql:/docker-entrypoint-initdb.d/10-docker_postgres_init.sql
  #     - ./setup/db/11-docker_postgres_keycloak_init.sql:/docker-entrypoint-initdb.d/11-docker_postgres_keycloak_init.sql
  #   ports:
  #     - '127.0.0.1:5401:5432'
  #   command: postgres -c max_prepared_transactions=150

  # postgres-region2:
  #   image: 'postgres:16.4-alpine3.20@sha256:d898b0b78a2627cb4ee63464a14efc9d296884f1b28c841b0ab7d7c42f1fffdf'
  #   restart: always
  #   environment:
  #     POSTGRES_DB: speckle
  #     POSTGRES_USER: speckle
  #     POSTGRES_PASSWORD: speckle
  #   volumes:
  #     - postgres-region2-data:/var/lib/postgresql/data/
  #     - ./setup/db/10-docker_postgres_init.sql:/docker-entrypoint-initdb.d/10-docker_postgres_init.sql
  #     - ./setup/db/11-docker_postgres_keycloak_init.sql:/docker-entrypoint-initdb.d/11-docker_postgres_keycloak_init.sql
  #   ports:
  #     - '127.0.0.1:5402:5432'
  #   command: postgres -c max_prepared_transactions=150

  redis:
    image: 'valkey/valkey:8.1-alpine'
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - '127.0.0.1:6379:6379'

  minio:
    image: 'minio/minio:RELEASE.2023-05-18T00-05-36Z'
    command: server /data --console-address ":9001"
    restart: always
    volumes:
      - minio-data:/data
    ports:
      - '0.0.0.0:9000:9000'
      - '0.0.0.0:9001:9001'

  # minio-region1:
  #   image: 'minio/minio'
  #   command: server /data --console-address ":9001"
  #   restart: always
  #   volumes:
  #     - minio-region1-data:/data
  #   ports:
  #     - '127.0.0.1:9020:9000'
  #     - '127.0.0.1:9021:9001'

  # minio-region2:
  #   image: 'minio/minio'
  #   command: server /data --console-address ":9001"
  #   restart: always
  #   volumes:
  #     - minio-region2-data:/data
  #   ports:
  #     - '127.0.0.1:9040:9000'
  #     - '127.0.0.1:9041:9001'

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.5
    depends_on:
      - postgres
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: speckle
      KC_DB_PASSWORD: speckle
      KC_HOSTNAME: 127.0.0.1
      KC_HOSTNAME_PORT: 9000
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8443:8443
      - 9010:9000
      - 8090:8080
    command: start-dev --import-realm
    volumes:
      - ./setup/keycloak:/opt/keycloak/data/import

  maildev:
    restart: always
    image: maildev/maildev
    ports:
      - '127.0.0.1:1080:1080'
      - '127.0.0.1:1025:1025'

  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@localhost.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   ports:
  #     - '127.0.0.1:16543:80'
  #   depends_on:
  #     - postgres

  # redis_insight:
  #   image: redislabs/redisinsight:latest
  #   restart: always
  #   volumes:
  #     - redis_insight-data:/db
  #   ports:
  #     - '127.0.0.1:8001:8001'
  #   depends_on:
  #     - redis

  speckle-ingress:
    # build:
    #   context: .
    #   dockerfile: utils/docker-compose-ingress/Dockerfile
    platform: linux/amd64
    image: registry.siruijie.com.cn/speckle/speckle-docker-compose-ingress:local
    restart: always
    ports:
      - '0.0.0.0:80:8080'
    environment:
      FILE_SIZE_LIMIT_MB: '1536'
      NGINX_ENVSUBST_OUTPUT_DIR: '/etc/nginx'
    depends_on:
      - speckle-server
      - speckle-frontend-2

  speckle-frontend-2:
    build:
      context: .
      dockerfile: packages/frontend-2/Dockerfile-192
    platform: linux/amd64
    image: speckle/speckle-frontend-2:local
    restart: always
    environment:
      NUXT_PUBLIC_SERVER_NAME: 'local'
      NUXT_PUBLIC_API_ORIGIN: 'http://192.168.154.28'
      NUXT_PUBLIC_BASE_URL: 'http://192.168.154.28'
      NUXT_PUBLIC_BACKEND_API_ORIGIN: 'http://speckle-server:3000'
      NUXT_PUBLIC_LOG_LEVEL: 'warn'
      NUXT_REDIS_URL: 'redis://redis'
      LOG_LEVEL: 'info'
      LOG_PRETTY: 'true'
      NUXT_PUBLIC_FF_LARGE_FILE_IMPORTS_ENABLED: 'true'
      NUXT_PUBLIC_FF_NEXT_GEN_FILE_IMPORTER_ENABLED: 'true'
    depends_on:
      - speckle-server

  speckle-server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    platform: linux/amd64
    image: speckle/speckle-server:local
    restart: always
    ports:
      - '0.0.0.0:3300:3000'
    healthcheck:
      test:
        - CMD
        - node
        - -e
        - "try { require('node:http').request({headers: {'Content-Type': 'application/json'}, port:3000, hostname:'127.0.0.1', path:'/readiness', method: 'GET', timeout: 2000 }, (res) => { body = ''; res.on('data', (chunk) => {body += chunk;}); res.on('end', () => {process.exit(res.statusCode != 200 || body.toLowerCase().includes('error') ? 1 : 0);}); }).end(); } catch { process.exit(1); }"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 90s
    environment:
      CANONICAL_URL: 'http://192.168.154.28'
      PRIVATE_OBJECTS_SERVER_URL: 'http://speckle-server:3000'
      SESSION_SECRET: 'localdev-session-secret'
      STRATEGY_LOCAL: 'true'
      LOG_LEVEL: 'info'
      LOG_PRETTY: 'true'
      POSTGRES_URL: 'postgres'
      POSTGRES_USER: 'speckle'
      POSTGRES_PASSWORD: 'speckle'
      POSTGRES_DB: 'speckle'
      REDIS_URL: 'redis://redis'
      PREVIEW_SERVICE_USE_PRIVATE_OBJECTS_SERVER_URL: 'true'
      PREVIEW_SERVICE_REDIS_URL: 'redis://redis'
      FILEIMPORT_SERVICE_USE_PRIVATE_OBJECTS_SERVER_URL: 'true'
      FILEIMPORT_SERVICE_REDIS_URL: 'redis://redis'
      S3_ENDPOINT: 'http://192.168.154.28:9000'
      S3_PUBLIC_ENDPOINT: 'http://192.168.154.28:9000'
      S3_ACCESS_KEY: 'minioadmin'
      S3_SECRET_KEY: 'minioadmin'
      S3_BUCKET: 'speckle-server'
      S3_CREATE_BUCKET: 'true'
      S3_REGION: ''
      FILE_SIZE_LIMIT_MB: 1536
      EMAIL_FROM: 'no-reply@example.org'
      EMAIL_SECURE: 'false'
      EMAIL_REQUIRE_TLS: 'false'
      FRONTEND_ORIGIN: 'http://192.168.154.28'
      ONBOARDING_STREAM_URL: 'https://latest.speckle.systems/projects/843d07eb10'
      FILEIMPORT_QUEUE_POSTGRES_URL: 'postgresql://speckle:speckle@postgres/speckle'
      FF_NEXT_GEN_FILE_IMPORTER_ENABLED: 'true'
      SUPER_REGISTER_TOKEN: 'srj-super-admin-register'
      ADMIN_OVERRIDE_ENABLED: 'true'
      SDUI_URL: 'http://192.168.154.28:8082'
    depends_on:
      - postgres
      - redis
      - minio

  preview-service:
    # build:
    #   context: .
    #   dockerfile: packages/preview-service/Dockerfile
    platform: linux/amd64
    image: registry.siruijie.com.cn/speckle/speckle-preview-service:local
    restart: always
    mem_limit: '3000m'
    memswap_limit: '3000m'
    environment:
      HOST: '127.0.0.1'
      PORT: '3001'
      LOG_LEVEL: 'info'
      LOG_PRETTY: 'true'
      REDIS_URL: 'redis://redis'
    depends_on:
      - redis

  webhook-service:
    # build:
    #   context: .
    #   dockerfile: packages/webhook-service/Dockerfile
    platform: linux/amd64
    image: registry.siruijie.com.cn/speckle/speckle-webhook-service:local
    restart: always
    environment:
      LOG_LEVEL: 'info'
      LOG_PRETTY: 'true'
      PG_CONNECTION_STRING: 'postgres://speckle:speckle@postgres/speckle'
    depends_on:
      - speckle-server
      - postgres

  ifc-import-server:
    # build:
    #   context: .
    #   dockerfile: packages/ifc-import-service/Dockerfile
    # platform: linux/amd64
    image: registry.siruijie.com.cn/speckle/ifc-import-service:2.26
    restart: always
    environment:
      LOG_LEVEL: 'info'
      LOG_PRETTY: 'true'
      FILEIMPORT_QUEUE_POSTGRES_URL: 'postgresql://speckle:speckle@postgres/speckle'
    depends_on:
      - speckle-server
      - postgres

volumes:
  postgres-data:
  # postgres-region1-data:
  # postgres-region2-data:
  redis-data:
  pgadmin-data:
  # redis_insight-data:
  minio-data:
  # minio-region1-data:
  # minio-region2-data:
