{{- if .Values.dxf_import_service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-metrics" (include "dxf_import_service.name" $) }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "dxf_import_service.labels" . | indent 4 }}
spec:
  selector:
    app: {{ include "dxf_import_service.name" $ }}
    project: speckle-server
  ports:
    - protocol: TCP
      name: web
      port: 9094
      targetPort: metrics
{{- end }}
